apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - image: wil42/playground:v1
        name: dev
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: dev
